# Link for datafile - "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
consumpData <- read.table("household_power_consumption.txt", header=T, sep=";")
head(consumpData)
str(consumpData)
consumpData$Date <- as.Date(consumpData$Date, format="%d/%m/%Y")
consumpFeb <- subset (consumpData, (consumpData$Date == "2007-02-01") | (consumpData$Date == "2007-02-02") )
x <- paste(as.character(consumpFeb$Date), as.character(consumpFeb$Time))
consumpFeb$DateTime <- strptime(x, "%Y-%m-%d %H:%M:%S")
consumpFeb$Sub_metering_1 <- as.numeric(as.character(consumpFeb$Sub_metering_1))
consumpFeb$Sub_metering_2 <- as.numeric(as.character(consumpFeb$Sub_metering_2))
png("plot3.png")
plot(consumpFeb$DateTime, consumpFeb$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(consumpFeb$DateTime, consumpFeb$Sub_metering_2, col="red")
lines(consumpFeb$DateTime, consumpFeb$Sub_metering_3, col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1 ","Sub_metering_2 ", "Sub_metering_3 "), lty=c(1,1), lwd=c(1,1))
dev.off()